FROM axllent/mailpit:latest

# Document the internal communication ports for the team
# 1025: Internal SMTP server port (FastAPI talks to this)
# 8025: Internal Web UI dashboard port (Nginx/Gateway references this)
EXPOSE 1025 8025