from enum import StrEnum

from pydantic import Field

from app.modules.user.validation import CreateUser, UserBaseResponse, UserTypeEnum


class EnrolleeApplicationStatusEnum(StrEnum):
  REGISTERED = "REGISTERED"
  PENDING_ACTIVATION = "PENDING_ACTIVATION"
  PROFILE_COMPLETE = "PROFILE_COMPLETE"
  EXAM_PENDING = "EXAM_PENDING"
  EXAM_FAILED = "EXAM_FAILED"
  EXAM_PASSED = "EXAM_PASSED"
  APPROVED = "APPROVED"
  ENROLLED = "ENROLLED"
  REJECTED = "REJECTED"

class CoursesEnum(StrEnum):
  COMPUTER_SCIENCE = "BACHELOR_OF_SCIENCE_IN_COMPUTER_SCIENCE"
  INFORMATION_TECHNOLOGY = "BACHELOR_OF_SCIENCE_IN_FORMATION_TECHNOLOGY"
  SOFTWARE_ENGINEERING = "BACHELOR_OF_SCIENCE_IN_SOFTWARE_ENGINEERING"
  DATA_SCIENCE = "BACHELOR_OF_SCIENCE_IN_DATA_SCIENCE"
  CYBER_SECURITY = "BACHELOR_OF_SCIENCE_IN_CYBER_SECURITY"
  NETWORKING = "BACHELOR_OF_SCIENCE_IN_NETWORKING"
  ARTIFICIAL_INTELLIGENCE = "BACHELOR_OF_SCIENCE_IN_ARTIFICIAL_INTELLIGENCE"
  CLOUD_COMPUTING = "BACHELOR_OF_SCIENCE_IN_CLOUD_COMPUTING"
  WEB_DEVELOPMENT = "BACHELOR_OF_SCIENCE_IN_WEB_DEVELOPMENT"
  MOBILE_APP_DEVELOPMENT = "BACHELOR_OF_SCIENCE_IN_MOBILE_APP_DEVELOPMENT"
  EDUCATION = "BACHELOR_OF_SCIENCE_IN_EDUCATION"
  PSYCHOLOGY = "BACHELOR_OF_SCIENCE_IN_PSYCHOLOGY"
  BUSINESS_ADMINISTRATION = "BACHELOR_OF_SCIENCE_IN_BUSINESS_ADMINISTRATION"
  ACCOUNTING = "BACHELOR_OF_SCIENCE_IN_ACCOUNTING"
  FINANCE = "BACHELOR_OF_SCIENCE_IN_FINANCE"
  MARKETING = "BACHELOR_OF_SCIENCE_IN_MARKETING"
  HUMAN_RESOURCE_MANAGEMENT = "BACHELOR_OF_SCIENCE_IN_HUMAN_RESOURCE_MANAGEMENT"
  CRIMINOLOGY = "BACHELOR_OF_SCIENCE_IN_CRIMINOLOGY"
  NURSING = "BACHELOR_OF_SCIENCE_IN_NURSING"
  PUBLIC_HEALTH = "BACHELOR_OF_SCIENCE_IN_PUBLIC_HEALTH"
  ENVIRONMENTAL_SCIENCE = "BACHELOR_OF_SCIENCE_IN_ENVIRONMENTAL_SCIENCE"
  BIOLOGY = "BACHELOR_OF_SCIENCE_IN_BIOLOGY"
  CHEMISTRY = "BACHELOR_OF_SCIENCE_IN_CHEMISTRY"
  PHYSICS = "BACHELOR_OF_SCIENCE_IN_PHYSICS"
  MATHEMATICS = "BACHELOR_OF_SCIENCE_IN_MATHEMATICS"
  ECONOMICS = "BACHELOR_OF_SCIENCE_IN_ECONOMICS"
  POLITICAL_SCIENCE = "BACHELOR_OF_SCIENCE_IN_POLITICAL_SCIENCE"
  SOCIOLOGY = "BACHELOR_OF_SCIENCE_IN_SOCIOLOGY"
  PHILOSOPHY = "BACHELOR_OF_SCIENCE_IN_PHILOSOPHY"
  HISTORY = "BACHELOR_OF_SCIENCE_IN_HISTORY"
  LITERATURE = "BACHELOR_OF_SCIENCE_IN_LITERATURE"
  ART = "BACHELOR_OF_SCIENCE_IN_ART"
  MUSIC = "BACHELOR_OF_SCIENCE_IN_MUSIC"
  THEATER = "BACHELOR_OF_SCIENCE_IN_THEATER"
  OTHER = "OTHER"

class EnrolleeResponse(UserBaseResponse):
  """Enrollee details"""

  model_config = {"from_attributes": True}


class CreateEnrollee(CreateUser):
  previous_school: str = Field(..., min_length=2, max_length=150, examples=["Farrell-Shields University"])
  chosen_course: CoursesEnum = Field(..., description="The course the enrollee is applying for.", examples=[CoursesEnum.INFORMATION_TECHNOLOGY.value])
  application_status: EnrolleeApplicationStatusEnum = EnrolleeApplicationStatusEnum.REGISTERED
  user_type: UserTypeEnum = UserTypeEnum.ENROLLEE
  is_verified: bool = False
