"""expand_employee_table

Revision ID: 0533fa47f1d2
Revises: 691329bb2f8d
Create Date: 2026-09-02 04:54:52.541869

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.modules.employee.validation import (
  BackgroundCheckStatusEnum,
  EmployeeStatusEnum,
  EmploymentTypeEnum,
  HighestEducationEnum,
  PayFrequencyEnum,
  WorkArrangementEnum,
)

# revision identifiers, used by Alembic.
revision: str = "0533fa47f1d2"
down_revision: str | Sequence[str] | None = "691329bb2f8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""

  # 1. Pre-create custom Enum types in PostgreSQL so they resolve in DDL below
  sa_employment_type_enum = sa.Enum(EmploymentTypeEnum, name="employmenttypeenum")
  sa_employee_status_enum = sa.Enum(EmployeeStatusEnum, name="employeestatusenum")
  sa_work_arrangement_enum = sa.Enum(WorkArrangementEnum, name="workarrangementenum")
  sa_highest_education_enum = sa.Enum(HighestEducationEnum, name="highesteducationenum")
  sa_background_check_status_enum = sa.Enum(
    BackgroundCheckStatusEnum, name="backgroundcheckstatusenum"
  )
  sa_pay_frequency_enum = sa.Enum(PayFrequencyEnum, name="payfrequencyenum")

  bind = op.get_bind()
  sa_employment_type_enum.create(bind, checkfirst=True)
  sa_employee_status_enum.create(bind, checkfirst=True)
  sa_work_arrangement_enum.create(bind, checkfirst=True)
  sa_highest_education_enum.create(bind, checkfirst=True)
  sa_background_check_status_enum.create(bind, checkfirst=True)
  sa_pay_frequency_enum.create(bind, checkfirst=True)

  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "employees",
    sa.Column("employment_type", sa_employment_type_enum, nullable=True),
  )
  op.add_column(
    "employees",
    sa.Column(
      "employee_status",
      sa_employee_status_enum,
      server_default="ACTIVE",
      nullable=False,
    ),
  )
  op.add_column("employees", sa.Column("probation_end_date", sa.Date(), nullable=True))
  op.add_column("employees", sa.Column("date_regularized", sa.Date(), nullable=True))
  op.add_column("employees", sa.Column("date_separated", sa.Date(), nullable=True))
  op.add_column(
    "employees", sa.Column("separation_reason", sa.String(length=250), nullable=True)
  )
  op.add_column(
    "employees",
    sa.Column("work_arrangement", sa_work_arrangement_enum, nullable=True),
  )
  op.add_column(
    "employees", sa.Column("job_title", sa.String(length=150), nullable=True)
  )
  op.add_column("employees", sa.Column("reports_to_id", sa.Integer(), nullable=True))
  op.add_column(
    "employees", sa.Column("office_location", sa.String(length=100), nullable=True)
  )
  op.add_column(
    "employees", sa.Column("extension_number", sa.String(length=20), nullable=True)
  )
  op.add_column(
    "employees", sa.Column("work_email", sa.String(length=255), nullable=True)
  )
  op.add_column(
    "employees", sa.Column("teaching_load_units", sa.Integer(), nullable=True)
  )
  op.add_column(
    "employees",
    sa.Column("advisory_class_section", sa.String(length=50), nullable=True),
  )
  op.add_column(
    "employees",
    sa.Column("highest_education", sa_highest_education_enum, nullable=True),
  )
  op.add_column(
    "employees", sa.Column("alma_mater", sa.String(length=200), nullable=True)
  )
  op.add_column("employees", sa.Column("year_graduated", sa.Integer(), nullable=True))
  op.add_column(
    "employees", sa.Column("field_of_study", sa.String(length=200), nullable=True)
  )
  op.add_column(
    "employees",
    sa.Column("professional_license_number", sa.String(length=100), nullable=True),
  )
  op.add_column("employees", sa.Column("license_expiry", sa.Date(), nullable=True))
  op.add_column(
    "employees", sa.Column("years_of_prior_experience", sa.Integer(), nullable=True)
  )
  op.add_column(
    "employees",
    sa.Column(
      "nda_signed", sa.Boolean(), server_default=sa.text("false"), nullable=False
    ),
  )
  op.add_column(
    "employees",
    sa.Column(
      "background_check_status",
      sa_background_check_status_enum,
      nullable=True,
    ),
  )
  op.add_column(
    "employees", sa.Column("last_background_check_date", sa.Date(), nullable=True)
  )
  op.add_column(
    "employees",
    sa.Column("basic_salary", sa.Numeric(precision=12, scale=2), nullable=True),
  )
  op.add_column(
    "employees", sa.Column("salary_grade", sa.String(length=50), nullable=True)
  )
  op.add_column(
    "employees",
    sa.Column("pay_frequency", sa_pay_frequency_enum, nullable=True),
  )
  op.add_column("employees", sa.Column("currency", sa.String(length=3), nullable=True))
  op.add_column(
    "employees", sa.Column("last_performance_review_date", sa.Date(), nullable=True)
  )
  op.add_column(
    "employees", sa.Column("next_performance_review_date", sa.Date(), nullable=True)
  )
  op.add_column(
    "employees",
    sa.Column("latest_performance_rating", sa.String(length=50), nullable=True),
  )
  op.create_foreign_key(
    "fk_employees_reports_to_id",
    "employees",
    "employees",
    ["reports_to_id"],
    ["id"],
    use_alter=True,
  )
  op.drop_column("employees", "is_active")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "employees",
    sa.Column(
      "is_active",
      sa.BOOLEAN(),
      server_default=sa.text("true"),
      autoincrement=False,
      nullable=False,
    ),
  )
  op.drop_constraint("fk_employees_reports_to_id", "employees", type_="foreignkey")
  op.drop_column("employees", "latest_performance_rating")
  op.drop_column("employees", "next_performance_review_date")
  op.drop_column("employees", "last_performance_review_date")
  op.drop_column("employees", "currency")
  op.drop_column("employees", "pay_frequency")
  op.drop_column("employees", "salary_grade")
  op.drop_column("employees", "basic_salary")
  op.drop_column("employees", "last_background_check_date")
  op.drop_column("employees", "background_check_status")
  op.drop_column("employees", "nda_signed")
  op.drop_column("employees", "years_of_prior_experience")
  op.drop_column("employees", "license_expiry")
  op.drop_column("employees", "professional_license_number")
  op.drop_column("employees", "field_of_study")
  op.drop_column("employees", "year_graduated")
  op.drop_column("employees", "alma_mater")
  op.drop_column("employees", "highest_education")
  op.drop_column("employees", "advisory_class_section")
  op.drop_column("employees", "teaching_load_units")
  op.drop_column("employees", "work_email")
  op.drop_column("employees", "extension_number")
  op.drop_column("employees", "office_location")
  op.drop_column("employees", "reports_to_id")
  op.drop_column("employees", "job_title")
  op.drop_column("employees", "work_arrangement")
  op.drop_column("employees", "separation_reason")
  op.drop_column("employees", "date_separated")
  op.drop_column("employees", "date_regularized")
  op.drop_column("employees", "probation_end_date")
  op.drop_column("employees", "employee_status")
  op.drop_column("employees", "employment_type")
  # ### end Alembic commands ###

  # 2. Clean up now-unreferenced PostgreSQL Enum TYPEs (after columns removed)
  bind = op.get_bind()
  sa_employment_type_enum = sa.Enum(EmploymentTypeEnum, name="employmenttypeenum")
  sa_employee_status_enum = sa.Enum(EmployeeStatusEnum, name="employeestatusenum")
  sa_work_arrangement_enum = sa.Enum(WorkArrangementEnum, name="workarrangementenum")
  sa_highest_education_enum = sa.Enum(HighestEducationEnum, name="highesteducationenum")
  sa_background_check_status_enum = sa.Enum(
    BackgroundCheckStatusEnum, name="backgroundcheckstatusenum"
  )
  sa_pay_frequency_enum = sa.Enum(PayFrequencyEnum, name="payfrequencyenum")
  sa_employment_type_enum.drop(bind, checkfirst=True)
  sa_employee_status_enum.drop(bind, checkfirst=True)
  sa_work_arrangement_enum.drop(bind, checkfirst=True)
  sa_highest_education_enum.drop(bind, checkfirst=True)
  sa_background_check_status_enum.drop(bind, checkfirst=True)
  sa_pay_frequency_enum.drop(bind, checkfirst=True)
