"""update_student_id_removed_length_check

Revision ID: eca4a070338d
Revises: a7b21fc1b25b
Create Date: 2026-06-18 03:23:50.009948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eca4a070338d'
down_revision: Union[str, Sequence[str], None] = 'a7b21fc1b25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollees', 'application_status',
               existing_type=postgresql.ENUM('REGISTERED', 'PROFILE_COMPLETE', 'EXAM_PENDING', 'EXAM_FAILED', 'EXAM_PASSED', 'APPROVED', 'ENROLLED', name='applicationstatusenum'),
               type_=sa.Enum('REGISTERED', 'PROFILE_COMPLETE', 'EXAM_PENDING', 'EXAM_FAILED', 'EXAM_PASSED', 'APPROVED', 'ENROLLED', name='enrolleeapplicationstatusenum'),
               existing_nullable=False)
    op.alter_column('students', 'academic_status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'GRADUATED', 'ON_LEAVE', 'SUSPENDED', 'WITHDRAWN', name='academicstatusenum'),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'GRADUATED', 'ON_LEAVE', 'SUSPENDED', 'WITHDRAWN', name='studentacademicstatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'academic_status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'GRADUATED', 'ON_LEAVE', 'SUSPENDED', 'WITHDRAWN', name='studentacademicstatusenum'),
               type_=postgresql.ENUM('ACTIVE', 'INACTIVE', 'GRADUATED', 'ON_LEAVE', 'SUSPENDED', 'WITHDRAWN', name='academicstatusenum'),
               existing_nullable=False)
    op.alter_column('enrollees', 'application_status',
               existing_type=sa.Enum('REGISTERED', 'PROFILE_COMPLETE', 'EXAM_PENDING', 'EXAM_FAILED', 'EXAM_PASSED', 'APPROVED', 'ENROLLED', name='enrolleeapplicationstatusenum'),
               type_=postgresql.ENUM('REGISTERED', 'PROFILE_COMPLETE', 'EXAM_PENDING', 'EXAM_FAILED', 'EXAM_PASSED', 'APPROVED', 'ENROLLED', name='applicationstatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
