"""update_columns_to_use_enums

Revision ID: a7b21fc1b25b
Revises: 624c9363288c
Create Date: 2026-06-18 01:23:05.398192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b21fc1b25b'
down_revision: Union[str, Sequence[str], None] = '624c9363288c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'department',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ADMISSIONS', 'INFORMATION_TECHNOLOGY', 'HUMAN_RESOURCES', 'FINANCE_AND_ACCOUNTING', 'REGISTRAR_OFFICE', 'FACILITIES_AND_OPERATIONS', 'MATHEMATICS', 'SCIENCE', 'COMPUTING_AND_INFORMATION_SCIENCES', 'ENGINEERING', 'BUSINESS_AND_MANAGEMENT', 'HUMANITIES_AND_SOCIAL_SCIENCES', 'LANGUAGES', name='departmentenum'),
               existing_nullable=False)
    op.alter_column('employees', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SYSTEM_ADMIN', 'IT_STAFF', 'HUMAN_RESOURCE', 'FINANCE', 'INVENTORY_MANAGER', 'REGISTRAR', 'ACADEMIC_LEAD', 'TEACHING_STAFF', 'LIBRARIAN', 'ADMINISTRATIVE_STAFF', 'EXECUTIVE', name='employeeroleenum'),
               existing_nullable=False)
    op.alter_column('enrollees', 'application_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('REGISTERED', 'PROFILE_COMPLETE', 'EXAM_PENDING', 'EXAM_FAILED', 'EXAM_PASSED', 'APPROVED', 'ENROLLED', name='enrolleeapplicationstatusenum'),
               existing_nullable=False)
    op.alter_column('students', 'academic_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'GRADUATED', 'ON_LEAVE', 'SUSPENDED', 'WITHDRAWN', name='studentacademicstatusenum'),
               existing_nullable=False)
    op.alter_column('tokens', 'token_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'ACCESS', 'BEARER', 'REFRESH', name='tokentypeenum'),
               existing_nullable=False)
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ENROLLEE', 'STUDENT', 'EMPLOYEE', name='usertypeenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_type',
               existing_type=sa.Enum('ENROLLEE', 'STUDENT', 'EMPLOYEE', name='usertypeenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('tokens', 'token_type',
               existing_type=sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'ACCESS', 'BEARER', 'REFRESH', name='tokentypeenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('students', 'academic_status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'GRADUATED', 'ON_LEAVE', 'SUSPENDED', 'WITHDRAWN', name='studentacademicstatusenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('enrollees', 'application_status',
               existing_type=sa.Enum('REGISTERED', 'PROFILE_COMPLETE', 'EXAM_PENDING', 'EXAM_FAILED', 'EXAM_PASSED', 'APPROVED', 'ENROLLED', name='enrolleeapplicationstatusenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('employees', 'role',
               existing_type=sa.Enum('SYSTEM_ADMIN', 'IT_STAFF', 'HUMAN_RESOURCE', 'FINANCE', 'INVENTORY_MANAGER', 'REGISTRAR', 'ACADEMIC_LEAD', 'TEACHING_STAFF', 'LIBRARIAN', 'ADMINISTRATIVE_STAFF', 'EXECUTIVE', name='employeeroleenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('employees', 'department',
               existing_type=sa.Enum('ADMISSIONS', 'INFORMATION_TECHNOLOGY', 'HUMAN_RESOURCES', 'FINANCE_AND_ACCOUNTING', 'REGISTRAR_OFFICE', 'FACILITIES_AND_OPERATIONS', 'MATHEMATICS', 'SCIENCE', 'COMPUTING_AND_INFORMATION_SCIENCES', 'ENGINEERING', 'BUSINESS_AND_MANAGEMENT', 'HUMANITIES_AND_SOCIAL_SCIENCES', 'LANGUAGES', name='departmentenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
