"""add_employee_related_tables

Revision ID: 380e59bad4e5
Revises: 0533fa47f1d2
Create Date: 2026-09-02 06:21:11.055414

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.modules.employee.validation import (
  BankAccountTypeEnum,
  CompensationChangeReasonEnum,
  EmployeeDocumentTypeEnum,
  HighestEducationEnum,
  LeaveTypeEnum,
  PayFrequencyEnum,
  PerformanceRatingEnum,
)

# revision identifiers, used by Alembic.
revision: str = "380e59bad4e5"
down_revision: str | Sequence[str] | None = "0533fa47f1d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""

  # 1. Pre-create custom Enum types in PostgreSQL (bound instances with members)
  #    Use checkfirst=True so types that already exist from prior migrations
  #    (e.g. payfrequencyenum, highesteducationenum from expand_employee_table)
  #    do not error out.
  sa_bank_account_type_enum = sa.Enum(BankAccountTypeEnum, name="bankaccounttypeenum")
  sa_pay_frequency_enum = sa.Enum(PayFrequencyEnum, name="payfrequencyenum")
  sa_compensation_change_reason_enum = sa.Enum(
    CompensationChangeReasonEnum, name="compensationchangereasonenum"
  )
  sa_employee_document_type_enum = sa.Enum(
    EmployeeDocumentTypeEnum, name="employeedocumenttypeenum"
  )
  sa_highest_education_enum = sa.Enum(HighestEducationEnum, name="highesteducationenum")
  sa_leave_type_enum = sa.Enum(LeaveTypeEnum, name="leavetypeenum")
  sa_performance_rating_enum = sa.Enum(
    PerformanceRatingEnum, name="performanceratingenum"
  )

  bind = op.get_bind()
  sa_bank_account_type_enum.create(bind, checkfirst=True)
  sa_pay_frequency_enum.create(bind, checkfirst=True)
  sa_compensation_change_reason_enum.create(bind, checkfirst=True)
  sa_employee_document_type_enum.create(bind, checkfirst=True)
  sa_highest_education_enum.create(bind, checkfirst=True)
  sa_leave_type_enum.create(bind, checkfirst=True)
  sa_performance_rating_enum.create(bind, checkfirst=True)

  # 1b. Column-DDL reference only — use postgresql.ENUM with create_type=False
  #     so SQLAlchemy's `_on_table_create` auto-CREATE-TYPE hook is completely
  #     suppressed for these instances.  The actual TYPE is created by the
  #     explicit .create(checkfirst=True) pre-step above so the columns just
  #     reference an already-existing TYPE by name.
  PostgresENUM = sa.dialects.postgresql.ENUM
  ref_bank_account_type = PostgresENUM(name="bankaccounttypeenum", create_type=False)
  ref_pay_frequency = PostgresENUM(name="payfrequencyenum", create_type=False)
  ref_compensation_change_reason = PostgresENUM(
    name="compensationchangereasonenum", create_type=False
  )
  ref_employee_document_type = PostgresENUM(
    name="employeedocumenttypeenum", create_type=False
  )
  ref_highest_education = PostgresENUM(name="highesteducationenum", create_type=False)
  ref_leave_type = PostgresENUM(name="leavetypeenum", create_type=False)
  ref_performance_rating = PostgresENUM(name="performanceratingenum", create_type=False)

  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "employee_bank_accounts",
    sa.Column("employee_id", sa.Integer(), nullable=False),
    sa.Column("bank_name", sa.String(length=100), nullable=False),
    sa.Column("bank_branch", sa.String(length=100), nullable=True),
    sa.Column("routing_code", sa.String(length=50), nullable=True),
    sa.Column("account_number", sa.String(length=100), nullable=False),
    sa.Column("account_type", ref_bank_account_type, nullable=False),
    sa.Column("account_holder_name", sa.String(length=200), nullable=True),
    sa.Column("currency", sa.String(length=3), nullable=False),
    sa.Column(
      "is_primary",
      sa.Boolean(),
      server_default=sa.text("false"),
      nullable=False,
    ),
    sa.Column(
      "is_active",
      sa.Boolean(),
      server_default=sa.text("true"),
      nullable=False,
    ),
    sa.Column("verified_at", sa.Date(), nullable=True),
    sa.Column("notes", sa.String(length=500), nullable=True),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("deleted_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "ix_emp_bank_accounts_employee_id",
    "employee_bank_accounts",
    ["employee_id"],
    unique=False,
  )
  op.create_index(
    "ix_emp_bank_accounts_primary",
    "employee_bank_accounts",
    ["is_primary"],
    unique=False,
  )
  op.create_index(
    op.f("ix_employee_bank_accounts_id"),
    "employee_bank_accounts",
    ["id"],
    unique=False,
  )
  op.create_table(
    "employee_compensation_history",
    sa.Column("employee_id", sa.Integer(), nullable=False),
    sa.Column("effective_date", sa.Date(), nullable=False),
    sa.Column("end_date", sa.Date(), nullable=True),
    sa.Column("basic_salary", sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column("salary_grade", sa.String(length=50), nullable=True),
    sa.Column("pay_frequency", ref_pay_frequency, nullable=True),
    sa.Column("currency", sa.String(length=3), nullable=True),
    sa.Column("change_reason", ref_compensation_change_reason, nullable=True),
    sa.Column("notes", sa.String(length=500), nullable=True),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("deleted_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint(
      "employee_id",
      "effective_date",
      name="uq_emp_comp_history_employee_effective_date",
    ),
  )
  op.create_index(
    "ix_emp_comp_history_effective_date",
    "employee_compensation_history",
    ["effective_date"],
    unique=False,
  )
  op.create_index(
    "ix_emp_comp_history_employee_id",
    "employee_compensation_history",
    ["employee_id"],
    unique=False,
  )
  op.create_index(
    op.f("ix_employee_compensation_history_id"),
    "employee_compensation_history",
    ["id"],
    unique=False,
  )
  op.create_table(
    "employee_documents",
    sa.Column("employee_id", sa.Integer(), nullable=False),
    sa.Column("document_type", ref_employee_document_type, nullable=False),
    sa.Column("document_title", sa.String(length=200), nullable=False),
    sa.Column("file_name", sa.String(length=255), nullable=True),
    sa.Column("file_path", sa.String(length=500), nullable=True),
    sa.Column("file_url", sa.String(length=1000), nullable=True),
    sa.Column("mime_type", sa.String(length=100), nullable=True),
    sa.Column(
      "uploaded_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("expiry_date", sa.Date(), nullable=True),
    sa.Column("verified_by_id", sa.Integer(), nullable=True),
    sa.Column("notes", sa.String(length=500), nullable=True),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("deleted_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(
      ["verified_by_id"],
      ["employees.id"],
      name="fk_emp_docs_verified_by_id",
      ondelete="SET NULL",
      use_alter=True,
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "ix_emp_documents_employee_id",
    "employee_documents",
    ["employee_id"],
    unique=False,
  )
  op.create_index(
    "ix_emp_documents_expiry_date",
    "employee_documents",
    ["expiry_date"],
    unique=False,
  )
  op.create_index(
    "ix_emp_documents_verified_by_id",
    "employee_documents",
    ["verified_by_id"],
    unique=False,
  )
  op.create_index(
    op.f("ix_employee_documents_id"),
    "employee_documents",
    ["id"],
    unique=False,
  )
  op.create_table(
    "employee_education_history",
    sa.Column("employee_id", sa.Integer(), nullable=False),
    sa.Column("degree", ref_highest_education, nullable=False),
    sa.Column("field_of_study", sa.String(length=200), nullable=False),
    sa.Column("institution_name", sa.String(length=200), nullable=False),
    sa.Column("institution_location", sa.String(length=200), nullable=True),
    sa.Column("year_started", sa.Integer(), nullable=True),
    sa.Column("year_completed", sa.Integer(), nullable=True),
    sa.Column(
      "is_incomplete",
      sa.Boolean(),
      server_default=sa.text("false"),
      nullable=False,
    ),
    sa.Column("honors", sa.String(length=200), nullable=True),
    sa.Column("thesis_title", sa.String(length=500), nullable=True),
    sa.Column("diploma_document_id", sa.Integer(), nullable=True),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("deleted_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
      ["diploma_document_id"],
      ["employee_documents.id"],
      name="fk_emp_edu_diploma_doc_id",
      ondelete="SET NULL",
      use_alter=True,
    ),
    sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "ix_emp_edu_history_diploma_document_id",
    "employee_education_history",
    ["diploma_document_id"],
    unique=False,
  )
  op.create_index(
    "ix_emp_edu_history_employee_id",
    "employee_education_history",
    ["employee_id"],
    unique=False,
  )
  op.create_index(
    "ix_emp_edu_history_year_completed",
    "employee_education_history",
    ["year_completed"],
    unique=False,
  )
  op.create_index(
    op.f("ix_employee_education_history_id"),
    "employee_education_history",
    ["id"],
    unique=False,
  )
  op.create_table(
    "employee_leave_credits",
    sa.Column("employee_id", sa.Integer(), nullable=False),
    sa.Column("leave_type", ref_leave_type, nullable=False),
    sa.Column("fiscal_year", sa.String(length=20), nullable=False),
    sa.Column("total_credited", sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column("used", sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column("balance", sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column(
      "as_of_date",
      sa.Date(),
      server_default=sa.text("CURRENT_DATE"),
      nullable=False,
    ),
    sa.Column("notes", sa.String(length=500), nullable=True),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("deleted_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint(
      "employee_id",
      "leave_type",
      "fiscal_year",
      name="uq_emp_leave_credits_employee_type_fiscal_year",
    ),
  )
  op.create_index(
    "ix_emp_leave_credits_employee_id",
    "employee_leave_credits",
    ["employee_id"],
    unique=False,
  )
  op.create_index(
    op.f("ix_employee_leave_credits_id"),
    "employee_leave_credits",
    ["id"],
    unique=False,
  )
  op.create_table(
    "employee_performance_reviews",
    sa.Column("employee_id", sa.Integer(), nullable=False),
    sa.Column("review_date", sa.Date(), nullable=False),
    sa.Column("review_period", sa.String(length=50), nullable=False),
    sa.Column("reviewer_id", sa.Integer(), nullable=True),
    sa.Column("rating", ref_performance_rating, nullable=True),
    sa.Column("score_numeric", sa.Integer(), nullable=True),
    sa.Column("overall_comments", sa.Text(), nullable=True),
    sa.Column("goals_next_period", sa.Text(), nullable=True),
    sa.Column("employee_sign_off_date", sa.Date(), nullable=True),
    sa.Column("reviewer_sign_off_date", sa.Date(), nullable=True),
    sa.Column("next_review_date", sa.Date(), nullable=True),
    sa.Column("attachments_path", sa.String(length=500), nullable=True),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column(
      "created_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      sa.DateTime(),
      server_default=sa.text("now()"),
      nullable=False,
    ),
    sa.Column("deleted_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(
      ["reviewer_id"],
      ["employees.id"],
      name="fk_emp_perf_reviewer_id",
      ondelete="SET NULL",
      use_alter=True,
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "ix_emp_perf_reviews_employee_id",
    "employee_performance_reviews",
    ["employee_id"],
    unique=False,
  )
  op.create_index(
    "ix_emp_perf_reviews_review_date",
    "employee_performance_reviews",
    ["review_date"],
    unique=False,
  )
  op.create_index(
    "ix_emp_perf_reviews_reviewer_id",
    "employee_performance_reviews",
    ["reviewer_id"],
    unique=False,
  )
  op.create_index(
    op.f("ix_employee_performance_reviews_id"),
    "employee_performance_reviews",
    ["id"],
    unique=False,
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(
    op.f("ix_employee_performance_reviews_id"),
    table_name="employee_performance_reviews",
  )
  op.drop_index(
    "ix_emp_perf_reviews_reviewer_id",
    table_name="employee_performance_reviews",
  )
  op.drop_index(
    "ix_emp_perf_reviews_review_date",
    table_name="employee_performance_reviews",
  )
  op.drop_index(
    "ix_emp_perf_reviews_employee_id",
    table_name="employee_performance_reviews",
  )
  op.drop_table("employee_performance_reviews")
  op.drop_index(
    op.f("ix_employee_leave_credits_id"), table_name="employee_leave_credits"
  )
  op.drop_index("ix_emp_leave_credits_employee_id", table_name="employee_leave_credits")
  op.drop_table("employee_leave_credits")
  op.drop_index(
    op.f("ix_employee_education_history_id"),
    table_name="employee_education_history",
  )
  op.drop_index(
    "ix_emp_edu_history_year_completed",
    table_name="employee_education_history",
  )
  op.drop_index(
    "ix_emp_edu_history_employee_id",
    table_name="employee_education_history",
  )
  op.drop_index(
    "ix_emp_edu_history_diploma_document_id",
    table_name="employee_education_history",
  )
  op.drop_table("employee_education_history")
  op.drop_index(op.f("ix_employee_documents_id"), table_name="employee_documents")
  op.drop_index("ix_emp_documents_verified_by_id", table_name="employee_documents")
  op.drop_index("ix_emp_documents_expiry_date", table_name="employee_documents")
  op.drop_index("ix_emp_documents_employee_id", table_name="employee_documents")
  op.drop_table("employee_documents")
  op.drop_index(
    op.f("ix_employee_compensation_history_id"),
    table_name="employee_compensation_history",
  )
  op.drop_index(
    "ix_emp_comp_history_employee_id",
    table_name="employee_compensation_history",
  )
  op.drop_index(
    "ix_emp_comp_history_effective_date",
    table_name="employee_compensation_history",
  )
  op.drop_table("employee_compensation_history")
  op.drop_index(
    op.f("ix_employee_bank_accounts_id"), table_name="employee_bank_accounts"
  )
  op.drop_index("ix_emp_bank_accounts_primary", table_name="employee_bank_accounts")
  op.drop_index("ix_emp_bank_accounts_employee_id", table_name="employee_bank_accounts")
  op.drop_table("employee_bank_accounts")
  # ### end Alembic commands ###

  # 2. Clean up now-unreferenced PostgreSQL Enum TYPEs (after tables dropped).
  #    Use checkfirst=True so types still referenced by other tables (e.g.
  #    employees table columns using payfrequencyenum / highesteducationenum)
  #    are not dropped.
  bind = op.get_bind()
  sa_bank_account_type_enum = sa.Enum(BankAccountTypeEnum, name="bankaccounttypeenum")
  sa_pay_frequency_enum = sa.Enum(PayFrequencyEnum, name="payfrequencyenum")
  sa_compensation_change_reason_enum = sa.Enum(
    CompensationChangeReasonEnum, name="compensationchangereasonenum"
  )
  sa_employee_document_type_enum = sa.Enum(
    EmployeeDocumentTypeEnum, name="employeedocumenttypeenum"
  )
  sa_highest_education_enum = sa.Enum(HighestEducationEnum, name="highesteducationenum")
  sa_leave_type_enum = sa.Enum(LeaveTypeEnum, name="leavetypeenum")
  sa_performance_rating_enum = sa.Enum(
    PerformanceRatingEnum, name="performanceratingenum"
  )
  sa_bank_account_type_enum.drop(bind, checkfirst=True)
  sa_pay_frequency_enum.drop(bind, checkfirst=True)
  sa_compensation_change_reason_enum.drop(bind, checkfirst=True)
  sa_employee_document_type_enum.drop(bind, checkfirst=True)
  sa_highest_education_enum.drop(bind, checkfirst=True)
  sa_leave_type_enum.drop(bind, checkfirst=True)
  sa_performance_rating_enum.drop(bind, checkfirst=True)
