"""update_enrollee_application_status_and_add_previous_application_status

Revision ID: 1684c5abd171
Revises: eca4a070338d
Create Date: 2026-09-01 12:33:14.953964

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.modules.enrollee.validation import EnrolleeApplicationStatusEnum

# revision identifiers, used by Alembic.
revision: str = "1684c5abd171"
down_revision: str | Sequence[str] | None = "eca4a070338d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###

  sa_application_status_enum = sa.Enum(
    EnrolleeApplicationStatusEnum, name="applicationstatusenum"
  )
  sa_application_status_enum.create(op.get_bind(), checkfirst=True)

  op.add_column(
    "enrollees",
    sa.Column(
      "previous_application_status",
      sa_application_status_enum,
      nullable=True,
    ),
  )
  op.alter_column(
    "enrollees",
    "application_status",
    existing_type=sa_application_status_enum,
    type_=sa_application_status_enum,
    nullable=True,
    postgresql_using="application_status::applicationstatusenum",
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "enrollees",
    "application_status",
    existing_type=sa.Enum(
      EnrolleeApplicationStatusEnum, name="enrolleeapplicationstatusenum"
    ),
    type_=sa.Enum(EnrolleeApplicationStatusEnum),
    nullable=False,
  )
  op.drop_column("enrollees", "previous_application_status")
  # ### end Alembic commands ###
