"""update_student_id_removed_length_check

Revision ID: eca4a070338d
Revises: a7b21fc1b25b
Create Date: 2026-06-18 03:23:50.009948

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eca4a070338d"
down_revision: str | Sequence[str] | None = "a7b21fc1b25b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "students",
    "student_id",
    existing_type=sa.String(length=18),
    type_=sa.String(),
    existing_nullable=False,
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "students",
    "student_id",
    existing_type=sa.String(),
    type_=sa.String(length=18),
    existing_nullable=False,
  )

  op.create_check_constraint(
    "ck_student_number_length", "students", "length(student_number) = 18"
  )
  # ### end Alembic commands ###
