.PHONY: install-deps update-deps build dev generate preview postinstall

PROJECT_NAME := nuxt4


install-deps:
	pnpm install


update-deps:
	pnpm update --recursive --latest --interactive


build:
	pnpm build


dev:
	pnpm dev


generate:
	pnpm generate


preview:
	pnpm preview


postinstall:
	pnpm postinstall