.PHONY: install-deps update-deps build dev generate preview postinstall \
        full-fix test lint lint-fix format format-check typecheck

PROJECT_NAME := nuxt4


install-deps:
	pnpm install

update-deps:
	pnpm update --recursive --latest --interactive

build:
	pnpm build

dev:
	pnpm dev

generate:
	pnpm generate

preview:
	pnpm preview

postinstall:
	pnpm postinstall

full-fix:
	pnpm full:fix

test:
	pnpm test

lint:
	pnpm lint

lint-fix:
	pnpm lint:fix

format:
	pnpm format

format-check:
	pnpm format:check

typecheck:
	pnpm typecheck
